Sitecore/docker-images

sitecore/8.2 rev. 170407/Dockerfile
sitecore/8.2 rev. 170614/Dockerfile
sitecore/8.2 rev. 170728/Dockerfile
sitecore/8.2 rev. 171121/Dockerfile
sitecore/9.0.0 rev. 171002 SQL/Dockerfile
sitecore/9.0.0 rev. 171002 XM1 CD/Dockerfile
sitecore/9.0.0 rev. 171002 XM1 CM/Dockerfile
sitecore/9.0.1 rev. 171219 SQL/Dockerfile
sitecore/9.0.1 rev. 171219 Solr/Dockerfile
sitecore/9.0.1 rev. 171219 XM1 CD/Dockerfile
sitecore/9.0.1 rev. 171219 XM1 CM/Dockerfile

Changes done to Dockerfiles for SC 9.0.1 rev. 171219
- Create SITEPATH variable to centralize definition of Website folder
- Replace ADD with COPY to follow best practices: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy

COPY instead of ADD + Environment variable SITEPATH

---

sitecore/9.0.1 rev. 171219 XM1 CD/Dockerfile
sitecore/9.0.1 rev. 171219 XM1 CM/Dockerfile

**Included Changes:**
- Data folder out of Website folder
- Data folder defined as a volume for persistence and to support license.xml file out of the image
- Data folder is emptied to support becoming a volume
- license.xml file is deleted from the image (along with other content in Data folder)
- Support to make Website folder also a volume (only at debugging time)
- Demo with VS2017 available soon with support for:
- Local Website at debugging time (no need for synchronization)
- Website folder embedded in the image at runtime.
- Website folder files automatically copied from image to Development environment (if missing) (same as databases).
- Attach to IIS process from VS2017
**Caveats:**
- Website folder has been moved to a different location
- Only implemented over "Sitecore 9.0.1 …

Data folder (and license.xml) as volume among other

---

Build.ps1

This is a tiny change to support pushing to the remote repository even if no changes are detected locally.
For performance reasons, it may be convenient building the images locally without pushing them every time to the remote repository. Once the images are validated and do not need additional changes then is time to push them to the remote repository.
With this change, the Build.ps1 file will support this scenario by providing the new parameter -ForcePush which will make the script push the images even if no changes are detected locally. Please notice that -SkipPush has more priority than -ForcePush, meaning that if -SkipPush is passed then -ForcePush will be ignored.

Support pushing to remote repository without local changes

---

CheckSources.ps1

Building images is a long-running task and missing source files is a common cause of failure.
The new script allows detecting missing source files before building the images.
**Suggestion**
This script may be used as validation for the existing Build.ps1 file to avoid the need of calling it explicitly.

Add CheckSources.ps1 to allow checking for missing source files

---

modules/Sitecore.DockerImages.Management/install.ps1

Changed install file to use PSModulePath to determine the correct module folder. This solves a problem installing for PowerShell 6.

Updated install file to work with PowerShell 6

---

variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa-1.8.1-sqldev/build.json

duplicate tag on sitecore-xp-pse-5.0-sqldev:9.1.1, fix the typo.

typo, same tag name, rename from ltsc2019 to 1903

---

linux/9.2.0 rev. 002893/sitecore-xm-sql/attach-databases.sh
linux/9.2.0 rev. 002893/sitecore-xm-sql/boot.sh
linux/9.2.0 rev. 002893/sitecore-xp-sql/attach-databases.sh
linux/9.2.0 rev. 002893/sitecore-xp-sql/boot.sh

- Increased sqlcmd timeout values in case the SQL process is slow to start.
- Better checks for existing databases files in the attach script used when booting.

SQL Server on Linux fixes

---

modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1

Fixes #71 
Added parsing to remove trailing '\' from path.
PowerShell always adds a trailing slash when using autocomplete at the prompt. `C:\destination` becomes `c:\destination\` 
This was causing an issue with `$fileName = $filePath.Replace("$Destination\", "")`. Instead of just fixing / hacking that one line I added parsing on the destination parameter and replaced all occurences of the $Destination parameter with the $destinationPath variable.

Fix parsing on destination for Invoke-PackageRestore

---

modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1

In line 104, string `downloadSession` is used for SessionVariable of Invoke_webRequest. But this was not assigned back to `$sitecoreDownloadSession` which is used in actual package download. Due to this receiving asp.net customerror page response

Fix Sitecore Download Session variable issue

---

modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1

After XC was added the build order was messed up. We now ensure that xp roles (including xconnect and identity) is builder before XC which depends on those.

fixed build order after XC was added

---

modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1

Updated the build.ps1 to now also automatically build the latest version of Redis that is tagged.
This is required fr XC but was not being built previously.

Updated SitecoreImageBuilder to now build Redis image

---

windows/9.2.x/sitecore-xc/Dockerfile
windows/dependencies/sitecore-certificates/Dockerfile

The certificate name being used for CM was incorrectly named 'XC'.
This means that the engine couldn't not create an SSL connection to https://cm as the cert name didn't match.
Changing this allows the commerce engine to talk to the CM instance.

Certificate naming issue

---

windows/9.2.0/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.2.0/sitecore-assets/tools/entrypoints/iis/Production.ps1
windows/9.2.x/sitecore-xc-bizfx/Dockerfile
windows/9.2.x/sitecore-xc-engine/Dockerfile
windows/9.3.0/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/iis/Production.ps1

The xc-engine and bizfx did not deep copy the tools directory, and where therefore missing e.g. the entrypoint tools.
In addition a small fix for `development.ps1` and `production.ps1` to not exit when there is no `App_Config\Include` directory present (which is e.g. the case for xc-engine).

Fix: recursively copy tools for xc-engine and bizfx & development/production.ps1 fix

---

windows/9.3.0/sitecore-assets/tools/entrypoints/worker/Development.ps1
windows/tests/9.3.x/docker-compose-xconnect-worker.yml

Added a test file for xConnect-only (and dependencies) roles.

Adding development.ps1 entrypoint for xConnect worker images

---

modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1

fixed issue with some base images not automaticlly being included in the tags to build.
Before:
```
sitecore-assets:9.3.0-nanoserver-1809                                     True      False        0 {mcr.microsoft.com/windows/servercore:ltsc2019, mcr.microsoft.com/windows/nanoserver:1809}
sitecore-xm-spe-cm:9.3.0-windowsservercore-ltsc2019                       True      False       17 {sitecore-assets:9.3.0-nanoserver-1809, sitecore-xm-cm:9.3.0-windowsservercore-ltsc2019}
sitecore-xm-sxa-cm:9.3.0-windowsservercore-ltsc2019                       True      False       19 {sitecore-assets:9.3.0-nanoserver-1809, sitecore-xm-spe-cm:9.3.0-windowsservercore-ltsc2019}
```
> Notice that the xm-cm which is a dependency to xm-sxa-cm is missing.
After:
```
sitecore-assets:9.3.0-nanoserver-1809 …
```

fixed issue with some bases image not being included

---

windows/9.3.0/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/iis/Production.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/worker/Development.ps1
windows/9.3.x/sitecore-xp-sqldev/Boot.ps1

Changed the output messages to no longer use '###'. Instead now it shows the time in a common format. Also updated Development.ps1 to include a switch to override the watcher. I don't see the need for this script to have many options.

Standardize the time output.

---

Set-LicenseEnvironmentVariable.ps1

For me this is working across PS 6, PS 7 RC1, PS 5, CMD calling PS 5 and PS 6 in WSL1. This script will now also throw an error if the license string is too short indicating that something is wrong.

another try to get license script to work on ps5+6

---

Build.ps1

Now you can use the following options to filter what is built.
```powershell
.\Build.ps1 -SitecoreUsername here@here.com -SitecorePassword abc123 -SitecoreVersion 9.3.0 -Topology xm -WindowsVersion 1809 -IncludeSpe -IncludeSxa -IncludeJss -RebuildExisting
```

Provide a low complexity way for developers to filter out build options

---

Build.ps1

Now you have to explicitly specify that you want to skip building an existing image.
Thanks for the feedback @pbering .

Reversed behavior to avoid a breaking change.

---

Build.ps1
modules/SitecoreImageBuilder/1.0.0/Private/Get-LatestSupportedVersionTags.ps1
modules/SitecoreImageBuilder/1.0.0/Private/Initialize-BuildSpecifications.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Get-LatestSupportedVersion.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Invoke-Build.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Invoke-PackageRestore.ps1

Tried to reduce the number of times that the specs have to be loaded from disk. I found that numerous calls were made to the `Get-BuildSpecifications` function. When debugging in VSCode it took forever! It is however reasonable without debugging.
Also made an adjustment to the build.ps1 to not build two images unless the right topology was chosen.

Specifications improvements

---

windows/9.3.x/sitecore-xp-sqldev/Boot.ps1

I had problems with attaching databases when using process isolation (and XP 9.3).
To mitigate these problems I basically added the solution which I had before here: https://github.com/avivasolutionsnl/sitecore-docker/blob/master/xp/mssql/Boot.ps1

More robust sql Boot.ps1

---

windows/9.2.0/sitecore-assets/Dockerfile
windows/9.2.x/sitecore-xm-jss/Dockerfile
windows/9.2.x/sitecore-xm-jss/build.json
windows/9.2.x/sitecore-xp-jss/Dockerfile
windows/9.2.x/sitecore-xp-jss/build.json

- Download Node.js in the assets image
- Update _sitecore-xm-jss_ and _sitecore-xp-jss_ Dockerfiles to install Node.js for _ContentManagement_ and _Standalone_ roles
Fixes #130

Install Node.js for JSS images for Experience Editor

---

windows/9.2.0/sitecore-assets/Dockerfile
windows/9.3.0/sitecore-assets/Dockerfile

Identiy Server is based on Sitecore Host, which is based on ASP.NET Core 2.1.
.NET Core 2.2 runtime EOL'ed December 2019, which motivates installing
the correct .NET Core 2.1 runtime even more, as this is Microsoft's LTS
version.
Fixes #247

Replace ASP.NET Core Hosting Bundle 2.2 with 2.1

---

windows/9.x.x/sitecore-ps-jss/Dockerfile
windows/9.x.x/sitecore-ps-jss/config/PublishingService.config
windows/9.x.x/sitecore-ps/Dockerfile
windows/9.x.x/sitecore-ps/config/PublishingService.config
windows/9.x.x/sitecore-sxa-ps-jss/Dockerfile
windows/9.x.x/sitecore-sxa-ps-jss/config/PublishingService.config
windows/9.x.x/sitecore-sxa-ps/Dockerfile
windows/9.x.x/sitecore-sxa-ps/config/PublishingService.config
windows/9.x.x/sitecore-xc-ps/Dockerfile
windows/9.x.x/sitecore-xc-ps/config/PublishingService.config

Override Publishing Service RootUrl setting as described in #208. Now Publishing Dashboard does not display errors, items delivered to `web`:

Override Publishing Service RootUrl setting to fix publishing

---

Build.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Invoke-Build.ps1

I was building the images on my local Windows 10 and on a Windows Server 2019.
Locally it worked fine, on the server it crashed during SQL Server image build.
It found this hard-coded `--isolation 'hyperv'` and replaced it with `--isolation 'process'` on the server and all issues went away.
I suggest to add a parameter 'IsolationMode' to allow the caller to either use default, hyperv or process isolation, depending on the OS and it's capabilities (see https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility).

#256: Add IsolationMode parameter to build.ps1

---

windows/9.0.2/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.1.1/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.2.0/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.2.0/sitecore-assets/tools/entrypoints/sitecore-xc-engine/Development.ps1
windows/9.2.0/sitecore-assets/tools/entrypoints/xconnect/Development.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/sitecore-xc-engine/Development.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/worker/Development.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/xconnect/Development.ps1

allow watch dir task to start without having a symlink to c:/src (default was really made mandatory-ish).
personal opinion; default should not be .\src but rather .\publish or perhaps .\deploy - the folder name .\src infer source code dir by convention..

enable folder names different from src for watch dir task

---

windows/dependencies/sitecore-openjdk/Dockerfile

OpenJDK Version in dockerfile has been removed from the openjdk github, and there for does not install when built.  Updated to latest LTS version so solr won't fail to start 
Recommend finding another way to get the latest supported version of things or check requisites available in the initial build scripts

Update java version to LTS of openjdk

---

windows/9.0.2/sitecore-assets/tools/scripts/Watch-Directory.ps1
windows/9.1.1/sitecore-assets/tools/scripts/Watch-Directory.ps1
windows/9.2.0/sitecore-assets/tools/scripts/Watch-Directory.ps1
windows/9.3.0/sitecore-assets/tools/scripts/Watch-Directory.ps1

Fixes #306 
- Fixed Delete file event handler has issues:
-- Corrected `ErrorAction` - set to `Stop` so that `Remove-Item` operation throws the error.
-- Implemented retry mechanism - it will attempt to delete the file 300 times with 1 second waiting interval between attempts.

Watch-Directory.ps1 - deployment file sync issue fix

---

legacy/images/9.0.2 rev. 180604/windowsservercore/sitecore-xp-sqldev/Boot.ps1
legacy/images/9.1.0 rev. 001564/windowsservercore/sitecore-xp-sqldev/Boot.ps1
legacy/images/9.1.1 rev. 002459/windowsservercore/sitecore-xp-sqldev/Boot.ps1
legacy/images/9.2.0 rev. 002893/windowsservercore/sitecore-xp-sqldev/Boot.ps1
windows/9.3.x/sitecore-xp-sqldev/Boot.ps1
windows/9.x.x/sitecore-xp-sqldev/Boot.ps1

Fixed wrong arguments for SQL query string formatting in `Boot.ps1` scripts.

Fixed Boot.ps1 scripts for SQL dev servers

---

linux/9.3.x/sitecore-xp-sql/boot.sh

we're copying all of the files into /opt but boot.sh refers to ./opt (which can be a different meaning if called from a different location)

correct opt path in linux boot.sh

---

CHANGELOG.md
linux/9.3.x/sitecore-xp-sql/boot.sh

Set ServerName xConnect shards on 9.3XP SQL linux images

---

contributing/Test-SitecorePackagesJson.ps1

Added a check to skip packages if the URL is empty so that the script doesn't throw an exception.
Fixes #342

Skip empty URLs when testing sitecore-packages.json

---

windows/9.x.x/sitecore-xm-solr/managed-schema.default.911
windows/9.x.x/sitecore-xp-solr/managed-schema.default.911

Remove 9.1.1 schema parts that are not compatible with Solr 7.2.1.
Sortable text fields are available from Sorl 7.3 and Korean tokenizer factory are present from Solr 7.5.

Remove incompatible Solr schema parts from 9.1.1

---

.gitignore

Corrected .gitignore so that "/build/tools" are ignored.

---

build-images.yml

Switching to a self-hosted linux pool since the Microsoft-hosted agents ran out of space on an xp1 build

Change build pipeline agent to a self-hosted pool due to disk size limitation on Microsoft-hosted agents

---

build-images.yml

Ensuring the build trigger uses the correct group names

Switching namespaces to match internal names

---

.gitignore
Build.ps1
build/CHANGELOG.md
build/modules/SitecoreImageBuilder/1.0.0/Public/Format-BuildOutputToJson.ps1
build/modules/SitecoreImageBuilder/1.0.0/SitecoreImageBuilder.psd1

It is useful for other systems and automation to have output in a format that can be easily parsed. 
Fixes #
> Note the addition of `-OutputJson` to the command
```
.\Build.ps1 -InstallSourcePath C:\repository\ -SitecoreUsername j -SitecorePassword j -SitecoreVersion 10.0.0 -IncludeSpe -IncludeSxa -IncludeJss -IncludeSh -IncludeExperimental -OutputJson -OSVersion "1909","2004","ltsc2019"
```

Adding the ability to output the 'will be built' images to Json

---

Build.ps1
build/CHANGELOG.md

Provides the ability to skip module asset images which are often not needed. This reduces the friction to getting up and running.
Fixes #458 by providing the ability to `-SkipModuleAssets`
Fixes #460 
Can be tested with
`.\Build.ps1 -InstallSourcePath C:\repository\ -SitecoreUsername j -SitecorePassword j -SitecoreVersion 10.0.0 -IncludeSpe -IncludeSxa -IncludeJss -IncludeSh -IncludeExperimental -SkipModuleAssets`
and
`.\Build.ps1 -InstallSourcePath C:\repository\ -SitecoreUsername j -SitecorePassword j -SitecoreVersion 10.0.0 -IncludeSpe -IncludeSxa -IncludeJss -IncludeSh -IncludeExperimental`
- …

Adding ability to exclude asset images

---

build/INSTRUCTIONS.md

To decrease the learning curve and confusion, added a note at the top of INSTRUCTIONS.md suggesting users visit the official documentation site for getting started.

Redirecting instructions to official documentation

---

build/windows/10.0.x/sitecore-docker-tools-assets/build.json

to simplify the build process, adding a 10.0.1 version of the sitecore-docker-tools-assets image, similar to how other module asset images also got tagged with 10.0.1

Adding a 10.0.1 version of tools assets

---

README.md
build/CHANGELOG.md
build/IMAGES.md
build/linux/10.0.1/sitecore-roles/sitecore-modules-mssql/xp0-build.json
build/linux/10.0.1/sitecore-roles/sitecore-modules-mssql/xp1-build.json

Missing a few linux JSS 15.0.1 tags

Missing JSS 15.0.1 tag for Linux mssql roles
