README.md

As per previous conversations, the README file has been updated to clarify the need for the Docker Registry.

Update README file with information about the need of a Docker Registry

---

CHANGELOG.md
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa-1.8.1-cm/Dockerfile
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa-1.8.1-cm/Invoke-XdtTransform.ps1
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa-1.8.1-cm/build.json
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa-1.8.1-cm/install-package.json
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa-1.8.1-sqldev/Extract-Databases.ps1
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa-1.8.1-sqldev/Install-Databases.ps1
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa-1.8.1-sqldev/build.json
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa.1.8.1-cd/Dockerfile
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa.1.8.1-cd/Invoke-XdtTransform.ps1
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa.1.8.1-cd/build.json
variants/9.1.1/windowsservercore/sxa/sitecore-xm1-sxa.1.8.1-cd/install-package.json
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa-1.8.1-sqldev/Extract-Databases.ps1
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa-1.8.1-sqldev/Install-Databases.ps1
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa-1.8.1-sqldev/build.json
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa-1.8.1-standalone/Dockerfile
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa-1.8.1-standalone/Invoke-XdtTransform.ps1
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa-1.8.1-standalone/build.json
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa-1.8.1-standalone/install-package.json
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa.1.8.1-cd/Dockerfile
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa.1.8.1-cd/Invoke-XdtTransform.ps1
variants/9.1.1/windowsservercore/sxa/sitecore-xp-sxa.1.8.1-cd/build.json

now applying xdt transform files that is a part of the SXA WDP packages. This also fixes that SXA *XM* works as expected.

fixed sxa xdt transforms

---

CHANGELOG.md

updare readme.md

---

IMAGES.md

Fix the index link in the IMAGES.md so it works :)

fix index link in images.md

---

modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1

it's only one line moved but diff shows a lot of line ending changes also...

os type check moved out of build loop

---

windows/9.2.x/sitecore-xp-identity/Dockerfile

@pbering pointed out the missing -Recurse switch

Added -Recurse to copy tools folder content to identity containers.

---

build-images.yml

This PR contains an Azure Devops build change proposal. 
Please do not yet merge as it is currently untested.

Azure Devops build script change proposal

---

windows/9.0.x/sitecore-xm-solr/Dockerfile
windows/9.x.x/sitecore-xc-solr/Dockerfile
windows/9.x.x/sitecore-xm-solr/Dockerfile
windows/9.x.x/sitecore-xp-solr/Dockerfile
windows/dependencies/mssql-developer-2017/Dockerfile
windows/dependencies/sitecore-openjdk/Dockerfile
windows/dependencies/sitecore-redis/Dockerfile

Removing the Invoke-WebRequest for standardization.  Also leveraged existing format of the C:\downloads folder for downloads and expanding into appropriate destination.

Removing IWR and adding curl

---

windows/9.2.x/sitecore-xc-engine/config/shared/data/Environments/PlugIn.Search.PolicySet-1.0.0.json

Policy file with search scope names was missing for XC.

Fix: configure search scope names for XC

---

.gitignore
.vscode/settings.json
CHANGELOG.md
Download-PS-Prerequisites .ps1
IMAGES.md
README.md
modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1
sitecore-packages.json
windows/9.3.0/sitecore-assets/Dockerfile
windows/9.3.0/sitecore-assets/build.json
windows/9.3.x/sitecore-ps/Dockerfile
windows/9.3.x/sitecore-ps/build.json
windows/9.3.x/sitecore-ps/scripts/start.ps1
windows/9.x.x/sitecore-sxa-ps-sqldev/Dockerfile
windows/9.x.x/sitecore-sxa-ps-sqldev/Extract-Databases.ps1
windows/9.x.x/sitecore-sxa-ps-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-sxa-ps-sqldev/build.json
windows/9.x.x/sitecore-sxa-ps/Dockerfile
windows/9.x.x/sitecore-sxa-ps/build.json
windows/tests/9.3.x/docker-compose.xp.sxa.ps.yml

Add XP/SXA/PS Variant
Add download script and convert publishing service module to WDP. (If not exists in packages download folder the build will skip the XP/SXA/PS variant)
Update readme.md with publishing service info
Update images refs

Feature/9.3.0/publishing service 4.2

---

Download-PS-Prerequisites .ps1
README.md
modules/SitecoreImageBuilder/SitecoreImageBuilder.psm1
windows/9.x.x/sitecore-sxa-ps-sqldev/build.json
windows/9.x.x/sitecore-sxa-ps/build.json

update readme with ExperimentalTagBehavior for PS

add ExperimentalTagBehavior for PS

---

windows/9.x.x/sitecore-sxa-ps/build.json

CD fix on sxa ref on ps image

---

README.md

updated quick start documentation according to comments in issue #154

fixes #154

---

README.md

fixes #179

---

README.md

Added section for regular cleanup of docker hosts.

cleanup doc added, closes #109

---

windows/9.2.0/sitecore-assets/tools/entrypoints/iis/Production.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/iis/Production.ps1

Fix typo in entrypoint scripts

---

Build.ps1
modules/SitecoreImageBuilder/1.0.0/Private/Initialize-BuildSpecifications.ps1
modules/SitecoreImageBuilder/1.0.0/Private/Write-Message.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Invoke-Build.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Invoke-PackageRestore.ps1

Show report once all builds are complete.

#204 : Formatted build messages.

---

Update-Documentation.ps1

Fixed documentation files generation script.

---

modules/SitecoreImageBuilder/1.0.0/Private/Invoke-FileDownload.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Invoke-PackageRestore.ps1

This has been tested in the PowerShell 5.1 Console and VSCode. The progress bar does not render for the PowerShell ISE due to limitations with the console.
Have not tested in PowerShell Core or through a CI/CD setup.

#210 : Progress bar improvements.

---

windows/9.2.0/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.2.0/sitecore-assets/tools/entrypoints/iis/Production.ps1
windows/9.2.0/sitecore-assets/tools/entrypoints/sitecore-xc-engine/Development.ps1
windows/9.2.0/sitecore-assets/tools/entrypoints/sitecore-xc-engine/Production.ps1

As suggested by Michael West based on his changes on the 9.3.0 entrypoint scripts to display standardized time output, I've applied the same changes to the 9.2.0 entrypoint scripts

standardized time output

---

modules/SitecoreImageBuilder/1.0.0/Private/Invoke-FileDownload.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Invoke-PackageRestore.ps1

This change includes some error checking when running from an environment where the console properties are not available.
This has been tested in the Windows PowerShell ISE, Windows PowerShell Console, VSCode, and Azure DevOps.

Add progress output to the console when downloading packages

---

modules/SitecoreImageBuilder/1.0.0/Private/Invoke-FileDownload.ps1
modules/SitecoreImageBuilder/1.0.0/Public/Invoke-PackageRestore.ps1

This addresses the issue from #238 and one that @pbering has been so patient with. Please have a review and merge as soon as possible.

#238 : Fixed issue with out of bounds index.

---

windows/9.0.2/sitecore-assets/entrypoints/iis/Development.ps1
windows/9.0.2/sitecore-assets/entrypoints/iis/Production.ps1
windows/9.1.1/sitecore-assets/tools/entrypoints/iis/Development.ps1
windows/9.1.1/sitecore-assets/tools/entrypoints/iis/Production.ps1
windows/9.2.x/sitecore-xc-spe-sqldev/Install-Databases.ps1
windows/9.2.x/sitecore-xc-sxa-sqldev/Install-Databases.ps1
windows/9.2.x/sitecore-xc-sxa-storefront-sqldev/Install-Databases.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/sitecore-xc-engine/Development.ps1
windows/9.3.0/sitecore-assets/tools/entrypoints/sitecore-xc-engine/Production.ps1
windows/9.3.x/sitecore-xc-spe-sqldev/Install-Databases.ps1
windows/9.3.x/sitecore-xc-sxa-sqldev/Install-Databases.ps1
windows/9.3.x/sitecore-xc-sxa-storefront-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-jss-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-ps-jss-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-ps-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-spe-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-sxa-jss-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-sxa-ps-jss-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-sxa-ps-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-sxa-sqldev/Install-Databases.ps1
windows/9.x.x/sitecore-xc-sqldev/Attach-Databases.ps1
windows/9.x.x/sitecore-xc-sqldev/Detach-Databases.ps1
windows/9.x.x/sitecore-xm-sqldev/Boot.ps1
windows/9.x.x/sitecore-xp-sqldev/Boot.ps1

This is to fix the remaining scripts to use the new log message format.

Updated formatting of log messages.

---

windows/9.x.x/sitecore-sxa-ps-jss-sqldev/build.json

Fixes #251 
Corrected Publishing Service installation for `sitecore-xm-sxa-ps-jss-sqldev` and `sitecore-xp-sxa-ps-jss-sqldev` images.

Corrected Publishing Service installation 

---

windows/tests/9.3.x/docker-compose.xm.jss.yml

Sc.9.3.0 XM JSS CD: Fixed JSS module installation.

---

README.md
windows/tests/9.2.x/.env
windows/tests/9.3.x/.env

Just adding some simple documentation when a user is pulling containers using a Registry. Updating the documentation and env files should help a user.

Simple Container Registry usage documentation update

---

build-images.yml

Currently only done for the Windows images. Work in progress for including other changes that @bplasmeijer is working on.

Switch Azure DevOps pipeline to leverage build.ps1

---

windows/9.3.x/sitecore-xm/config/cm/Web.config.xdt
windows/9.3.x/sitecore-xp/config/standalone/Web.config.xdt

Replace CSP instead of removing it completely

---

linux/9.3.x/sitecore-spe-sql/Dockerfile
linux/9.3.x/sitecore-sxa-sql/Dockerfile

FIX: chmod after copy

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
README.md
contributing/Sort-SitecorePackagesJson.ps1
contributing/Test-SitecorePackagesJson.ps1

Added:
- Guidelines
- Scripts for tidying up sitecore-packages.json
- GitHub issue template

adding contributor guidelines and tools

---

CHANGELOG.md
linux/9.3.x/sitecore-xp-solr/Dockerfile
linux/9.3.x/sitecore-xp-solr/build.json
linux/9.3.x/sitecore-xp-solr/initialize-solr.sh
linux/9.3.x/sitecore-xp-solr/managed-schema.default.930

Set default schema for base and XDB

Sitecore 9.3.0 XP/SXA Solr linux images.

---

CHANGELOG.md
IMAGES.md
README.md
linux/9.3.x/sitecore-sxa-ps-sql/Dockerfile
linux/9.3.x/sitecore-sxa-ps-sql/attach-databases.sh
linux/9.3.x/sitecore-sxa-ps-sql/build.json
linux/9.3.x/sitecore-sxa-ps-sql/install-databases.sh

Linux 9.3.0 SXA + publishing service

Linux SXA + publishing service

---

CHANGELOG.md
linux/9.3.x/sitecore-xp-sql/Dockerfile
linux/9.3.x/sitecore-xp-sql/InstallShards.ps1
linux/9.3.x/sitecore-xp-sql/build.json
linux/9.3.x/sitecore-xp-sql/replace_log.sh

Added initialized shard databases

SQL XP Linux shard added

---

build/windows/10.0.0/modules/ps-assets/Dockerfile
build/windows/10.0.0/modules/ps-assets/build.json
build/windows/10.0.0/modules/ps-assets/tools/Prepare-cd-assets.ps1
build/windows/10.x.x/sitecore-custom-base/xp-build.json

- Add specific Dockerfile for use by ps-assets (instead of using common)
- Add script to support copying specific files to the module/cd/content folder for ps-assets
- Add xp1-cd-sxa-jss-ps definition

Add XP1 CD Publishing Service components

---

README.md
build/CHANGELOG.md
build/IMAGES.md

Update readme and images community tags

Update README and IMAGES

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #
NO IMAGE CHANGES - simple documentation changes.

fixing url to contributing.md

---

build-images.yml

NO functionality change, cleaned up comments.

Simple cleanup of the yaml comments after many permutations

---

Build.ps1
README.md
build/CHANGELOG.md
build/IMAGES.md
build/modules/SitecoreImageBuilder/1.0.0/Private/Get-SupportedWindowsVersions.ps1
build/modules/SitecoreImageBuilder/1.0.0/Private/Get-WindowsServerCoreToNanoServerVersionMap.ps1

- [ Y ] I have added NEW image tags
- [ N ] I have made significant changes to existing images
20H2 support to allow running in process isolation.
Fixes #
- [ Y ] I have read and am familiar with the contents of [CONTRIBUTING.md](https://github.com/Sitecore/docker-images/blob/master/CONTRIBUTING.md)
- [ Y ] I have built the images locally (all relevant OS versions, including Linux if applicable)
.\Build.ps1 -InstallSourcePath C:\temp -SitecoreUsername XXX -SitecorePassword XXX -SitecoreVersion 9.2.0 -OSVersion 20H2 -Topology xm
- Ensure the build was done on a clean system (`docker system prune …

Update to support 2009

---

build/CHANGELOG.md
build/linux/10.0.x/modules/jss-assets/1500-build.json
build/linux/10.0.x/modules/jss-assets/1501-build.json
build/windows/10.x.x/sitecore-custom-base/xm-build.json
build/windows/10.x.x/sitecore-custom-base/xp-build.json
build/windows/10.x.x/sitecore-custom-base/xp0-build.json
build/windows/10.x.x/sitecore-custom-mssql/sitecore-custom-modules-mssql-init/xm-build.json
build/windows/10.x.x/sitecore-custom-mssql/sitecore-custom-modules-mssql-init/xp-build.json
build/windows/10.x.x/sitecore-custom-mssql/sitecore-custom-mssql/xm-build.json
build/windows/10.x.x/sitecore-custom-mssql/sitecore-custom-mssql/xp-build.json
build/windows/10.x.x/sitecore-custom-mssql/sitecore-custom-mssql/xp0-build.json

This PR adds JSS v15.0.1. This also fixes the sccpl transform files that are not run when Sitecore v10.0.1 was catered for in this repo.
Fixes https://github.com/Sitecore/docker-images/issues/474
```powershell
.\Build.ps1 -InstallSourcePath "z:\" -SitecoreUsername "fdsa" -SitecorePassword "fdsa" -Registry "cpasitecoredocker.azurecr.io" -RegistryUserName "fds" -RegistryPassword "fdsa" -Topology @("xm","xp","xp0") -OSVersion @("2009","2004","ltsc2019") -IncludeSpe -IncludeSxa -IncludeJss -SkipModuleAssets -SitecoreVersion @("10.0.0","10.0.1")
```

Adding JSS v15.0.1 to both 10.0.0 and 10.0.1

---

build-images.yml
build/CHANGELOG.md
build/INSTRUCTIONS.md
build/contributing/Test-SitecorePackagesJson.ps1
build/sitecore-packages.json

- Removed username/password from documentation.
- Fixed Test-SitecorePackages
- sorted entries in sitecore-packages.json

Documentation updates

---

build/sitecore-packages.json

Adding downlaod packages for jss 1501 (used by Linux)

---

build/sitecore-packages.json

Updating url and hash for JSS 15.0.1

---

build-images.yml

Fixed sitecoreRegistry variable name in conditions

---

build/Download-Module-Prerequisites.ps1

Restore SAT download during the build

---

README.md

Some organizations require whitelisting of domains/ip's for access, so added all Sitecore Container Registry domains to the readme. Feel free to adjust wording if desired.
**What this PR does / why we need it**: 
Adds scr domains to the readme, some organizations require whitelisting of domains/ip's.
Fixes internal reference number #468736
**Special notes for your reviewer**: 
Feel free to adjust wording as you see fit

Added details about scr domains

---

build/linux/10.1.0/sitecore-roles/sitecore-modules-mssql/xm1-build.json

Replacing XP1 with XM1 topology for headless

---

build/linux/10.1.0/base/sitecore-xp0-mssql/build.json
build/sitecore-packages.json

Sitecore 10.1.0 (WDP XPSingle packages) - the file downloaded using the link in sitecore-packages.json has a different revision.
Fixes #

Fixed Sitecore 10.1.0 (WDP XPSingle packages) revision

---

.gitignore
Build.ps1
build/CHANGELOG.md
build/Download-Module-Prerequisites.ps1
build/INSTRUCTIONS.md
build/coveo-for-sitecore-tools/Add-To-SitecorePackagesJson.ps1
build/coveo-for-sitecore-tools/Extract-Resources.ps1
build/coveo-for-sitecore-tools/Generate-Coveo-Assets-Folders.ps1
build/coveo-for-sitecore-tools/Generate-Coveo-BuildJson.ps1
build/coveo-for-sitecore-tools/Setup-Coveo-Build.ps1

- Adds coveo-for-sitecore-tools to allow building Coveo for Sitecore assets in Sitecore 10+. Using those assets, the clients will be able to launch a Sitecore instance in which Coveo will already be installed. They'll also be able to select the Coveo for Sitecore version they want. 
- None
- This PR contains scripts to setup the required files and folders to build Coveo for Sitecore assets. 
- It's designed to be compatible with Sitecore 10.0.0 or newer.
- No images were added or modified, everything happens locally when launching the Build.ps1 script with the 
`-CoveoVersion` parameter.
- A section has been added in the INSTRUCTIONS.md file to explain how to use the parameter.
- …

Add coveo-for-sitecore-tools to build Coveo for Sitecore assets
